spring:
  application:
    name: cookies-bot
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.137.137}:${MYSQL_PORT:3306}/db_bot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ${MYSQL_ROOT_PW:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

app:
  bot:
    qq: ${QQ_ID:1234567890}
    password: ${QQ_PW:123456abc.}
    cmd: 🍪
  setu:
    user:
      level-exp: 0, 4, 16, 64, 256, 1024, 4096, 16384, 65536, 262144, 1048576
      speak-exp: 1
      speak-exp-max-of-day: 1024
    setu:
      level-setu-max-of-day: 16, 24, 40, 72, 136, 264, 520, 1032, 2056, 4104, 8200
      uploadExp: 16
  lang:
    type: meow
    path: lang/langs.csv
    on-tag-localization: true
    localization-file-path: lang/tags.csv
  cmd:
    sudoers:
      - 570185461
      - 2394495949


