## 该配置为全局配置，对所有Session有效

# 可选，默认值为0.0.0.0
host: '127.0.0.1'

# 可选，默认值为8080
port: 6666

# 可选，默认由插件第一次启动时随机生成，建议手动指定
authKey: Ok4qMBWHGF6N7Fx5

# 可选，缓存大小，默认4096.缓存过小会导致引用回复与撤回消息失败
cacheSize: 65536

# 可选，是否开启websocket，默认关闭，建议通过Session范围的配置设置
enableWebsocket: false

# 可选，配置CORS跨域，默认为*，即允许所有域名
cors:
  - '*'

## 消息上报
report:
  # 功能总开关
  enable: true
  # 群消息上报
  groupMessage:
    report: true
  # 好友消息上报
  friendMessage:
    report: true
  # 临时消息上报
  tempMessage:
    report: true
  # 事件上报
  eventMessage:
    report: true
  # 上报URL
  destinations: ["http://127.0.0.1:7777/event/mirai"]
  # 上报时的额外Header
  extraHeaders: {}

## 心跳
heartbeat:
  # 功能总开关
  enable: false
  # 启动延迟
  delay: 1000
  # 心跳间隔
  period: 15000
  # 心跳上报URL
  destinations: []
  # 上报时的额外信息
  extraBody: {}
  # 上报时的额外头
  extraHeaders: {}